### ISSUE TITLE
Waybar和视频中演示的不一样

### ISSUE THREAD

**Issue by Fanccy315** [sgj123456/dotfiles#1]
![screen_shot_2023-08-25_22-40-37](https://github.com/sgj123456/dotfiles/assets/95154395/afe4f924-7378-4484-bcea-5bc1daf7a670)

**Comment by sgj123456** [comment]
![Cache_-23861927575acef3.png](https://github.com/sgj123456/dotfiles/assets/94758390/3623b4c1-26e4-4870-8e0f-c70f57c69ffd)

因为当时修改了一半开学了，这是现在的样子
